Additional parameters for ClassDef
This fixes error:
TypeError: ClassDef.__init__() missing 2 required positional arguments:
'col_offset' and 'parent'